version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - attach_workspace:
          at: my_workspace 
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test
      - run:
          command: echo 'writing to file' > my_workspace/file.txt
          name: Write to file
  job2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"

workflows:
  main-workflow:
    jobs:
      - build-and-test
      - job2

