version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - attach_workspace:
          at: my_workspace 
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py
          name: Test
      - run:
          command: echo 'writing to file' > my_workspace/file.txt
          name: Write to file
  job2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "hello from job2"
  deploy-party-job:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run: echo "Running scheduled job at $(date)"


workflows:
  version: 2
  workflow-z:
    jobs:
      - build-and-test
      - job2:
          requires:
            - build-and-test
  workflow-w:
    jobs:
      - job2
  lets-party:
    jobs:
      - deploy-party-job
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - master

